version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: vm_tips_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vm_tips_db
      MYSQL_USER: vm_tips_user
      MYSQL_PASSWORD: vm_tips_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
